### ISSUE TITLE
Bundler throws exception `ReferenceError: bundl is not defined`

### ISSUE THREAD

**Issue by MiguelCastillo** [MiguelCastillo/bit-bundler#12]
```
>> ReferenceError: bundl is not defined
>>     at /Users/mcastillo/Projects/bit-bundler/src/bundler.js:129:9
>>     at runMicrotasksCallback (node.js:337:7)
>>     at process._tickCallback (node.js:355:11)
```

**Comment by MiguelCastillo** [comment]
https://github.com/MiguelCastillo/bit-bundler/pull/13
